"""Generate the read-only ESD state signature table from the shipped player ESD.

Each (machine, state) is identified in memory by its id and its condition,
enter, exit and ongoing command counts. Signatures must be unique; the table is
pinned to the exact ESD bytes the owner-test package installs.
"""
import hashlib
import json
from pathlib import Path

from dsr_mw2.soulstruct_tools import configure, WORKSPACE as ROOT

ESD = ROOT / 'converted/dsr/action-trial-v1/chr/c0000.esd.dcx'
HEADER = ROOT / 'native/include/esd_state_table.hpp'


def rows(data):
    configure()
    from soulstruct.darksouls1r.ezstate.esd import ChrESD
    esd = ChrESD.from_bytes(data)
    out = []
    for machine, states in sorted(esd.state_machines.items()):
        for state_id, s in sorted(states.items()):
            out.append((machine, state_id, len(s.conditions), len(s.enter_commands),
                        len(s.exit_commands), len(s.ongoing_commands)))
    signatures = [r[1:] for r in out]
    if len(set(signatures)) != len(signatures):
        raise ValueError('ESD state signatures are ambiguous')
    return out


def main():
    data = ESD.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    table = rows(data)
    from soulstruct.dcx.core import decompress
    span = len(decompress(data)[0])
    lines = ['// Generated by tools/build_esd_state_table.py; do not edit.',
             '// Source: chr/c0000.esd.dcx sha256 ' + digest,
             '#pragma once', '#include "esd_state_probe.hpp"', '', 'namespace dsr_mw2 {',
             'inline constexpr std::size_t esd_state_span = %d;  // decompressed ESD bytes' % span,
             'inline constexpr EsdStateSignature esd_state_table[] = {']
    lines += ['    {%d,%d,%d,%d,%d,%d},' % r for r in table]
    lines += ['};', '} // namespace dsr_mw2', '']
    HEADER.write_text('\n'.join(lines))
    print(json.dumps({'esd_sha256': digest, 'states': len(table), 'span': span, 'header': str(HEADER.relative_to(ROOT))}))


if __name__ == '__main__':
    main()
