"""Generate the exact Bullet rows the adapter swaps for the SCAR-H M203 mode.

Bullet 600 is the Standard Bolt projectile every native gun shot uses; row
54014 is the M203 grenade. Both are taken from the shipped owner package and
pinned to its GameParam hash. Retail-derived bytes: not part of the public export.
"""
import hashlib
import json

from dsr_mw2.action_trial import OUT
from dsr_mw2.soulstruct_tools import configure, WORKSPACE as ROOT

HEADER = ROOT / 'native/include/scar_bullet_rows.hpp'
BOLT, GRENADE = 600, 54014


def main():
    configure()
    from soulstruct.darksouls1r.params import GameParamBND
    data = (OUT / 'param/GameParam/GameParam.parambnd.dcx').read_bytes()
    bullets = {k.rsplit('\\', 1)[-1]: v for k, v in GameParamBND.from_bytes(data).params.items()}['Bullet']
    bolt, grenade = bytes(bullets[BOLT]), bytes(bullets[GRENADE])
    if len(bolt) != len(grenade) or bolt == grenade:
        raise ValueError('Unexpected Bullet row layout')
    def array(name, raw):
        body = ','.join('0x%02x' % b for b in raw)
        return 'inline constexpr std::uint8_t %s[%d]={%s};' % (name, len(raw), body)
    digest = hashlib.sha256(data).hexdigest()
    HEADER.write_text('\n'.join([
        '// Generated by tools/build_scar_bullet_rows.py; do not edit.',
        '// Source: param/GameParam/GameParam.parambnd.dcx sha256 ' + digest,
        '#pragma once', '#include <cstdint>', '', 'namespace dsr_mw2 {',
        array('standard_bolt_bullet', bolt), array('m203_grenade_bullet', grenade),
        '} // namespace dsr_mw2', '']))
    print(json.dumps({'param_sha256': digest, 'row_bytes': len(bolt), 'header': str(HEADER.relative_to(ROOT))}))


if __name__ == '__main__':
    main()
